// Bundled geography suggestions for the Plan form. Chrome extensions cannot
// fetch remote lists (MV3 CSP), so both lists ship with the extension.
// Countries: full UN member list. Cities: hand-picked major cities for the
// countries this tool is most used in — any free-typed city still works.
export const COUNTRIES = [
  'Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Antigua and Barbuda', 'Argentina',
  'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados',
  'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina',
  'Botswana', 'Brazil', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia',
  'Cameroon', 'Canada', 'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia',
  'Comoros', 'Congo', 'Costa Rica', 'Croatia', 'Cuba', 'Cyprus', 'Czechia',
  'Democratic Republic of the Congo', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic',
  'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini',
  'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana',
  'Greece', 'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras',
  'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
  'Ivory Coast', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Kuwait',
  'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein',
  'Lithuania', 'Luxembourg', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
  'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico', 'Micronesia', 'Moldova', 'Monaco',
  'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal',
  'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North Korea', 'North Macedonia',
  'Norway', 'Oman', 'Pakistan', 'Palau', 'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay',
  'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar', 'Romania', 'Russia', 'Rwanda',
  'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Vincent and the Grenadines', 'Samoa',
  'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles',
  'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia',
  'South Africa', 'South Korea', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname',
  'Sweden', 'Switzerland', 'Syria', 'Taiwan', 'Tajikistan', 'Tanzania', 'Thailand',
  'Timor-Leste', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan',
  'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States',
  'Uruguay', 'Uzbekistan', 'Vanuatu', 'Vatican City', 'Venezuela', 'Vietnam', 'Yemen', 'Zambia',
  'Zimbabwe'
];

export const CITIES = {
  'pakistan': ['Karachi', 'Lahore', 'Islamabad', 'Rawalpindi', 'Faisalabad', 'Multan', 'Peshawar', 'Quetta', 'Sialkot', 'Gujranwala', 'Hyderabad', 'Bahawalpur'],
  'india': ['Mumbai', 'Delhi', 'Bengaluru', 'Hyderabad', 'Chennai', 'Kolkata', 'Pune', 'Ahmedabad', 'Jaipur', 'Lucknow', 'Surat', 'Chandigarh'],
  'bangladesh': ['Dhaka', 'Chattogram', 'Khulna', 'Sylhet', 'Rajshahi', 'Narayanganj', 'Gazipur', 'Comilla'],
  'sri lanka': ['Colombo', 'Kandy', 'Galle', 'Negombo', 'Jaffna', 'Kurunegala'],
  'nepal': ['Kathmandu', 'Pokhara', 'Lalitpur', 'Biratnagar'],
  'united arab emirates': ['Dubai', 'Abu Dhabi', 'Sharjah', 'Ajman', 'Ras Al Khaimah', 'Fujairah', 'Al Ain'],
  'saudi arabia': ['Riyadh', 'Jeddah', 'Mecca', 'Medina', 'Dammam', 'Khobar', 'Taif', 'Tabuk'],
  'qatar': ['Doha', 'Al Rayyan', 'Al Wakrah'],
  'kuwait': ['Kuwait City', 'Hawalli', 'Salmiya'],
  'oman': ['Muscat', 'Salalah', 'Sohar'],
  'bahrain': ['Manama', 'Muharraq', 'Riffa'],
  'jordan': ['Amman', 'Zarqa', 'Irbid', 'Aqaba'],
  'egypt': ['Cairo', 'Alexandria', 'Giza', 'Sharm El Sheikh', 'Hurghada', 'Luxor', 'Aswan', 'Mansoura'],
  'turkey': ['Istanbul', 'Ankara', 'Izmir', 'Bursa', 'Antalya', 'Adana', 'Gaziantep', 'Konya'],
  'united kingdom': ['London', 'Manchester', 'Birmingham', 'Leeds', 'Glasgow', 'Liverpool', 'Edinburgh', 'Bristol', 'Sheffield', 'Cardiff', 'Belfast', 'Nottingham'],
  'united states': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Francisco', 'Seattle', 'Miami', 'Boston', 'Atlanta', 'Denver', 'Las Vegas'],
  'canada': ['Toronto', 'Montreal', 'Vancouver', 'Calgary', 'Edmonton', 'Ottawa', 'Winnipeg', 'Quebec City', 'Hamilton', 'Mississauga'],
  'australia': ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide', 'Gold Coast', 'Canberra', 'Newcastle'],
  'new zealand': ['Auckland', 'Wellington', 'Christchurch', 'Hamilton'],
  'germany': ['Berlin', 'Hamburg', 'Munich', 'Cologne', 'Frankfurt', 'Stuttgart', 'Dusseldorf', 'Leipzig', 'Dortmund', 'Dresden'],
  'france': ['Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice', 'Nantes', 'Strasbourg', 'Bordeaux', 'Lille', 'Montpellier'],
  'spain': ['Madrid', 'Barcelona', 'Valencia', 'Seville', 'Zaragoza', 'Malaga', 'Bilbao', 'Granada'],
  'italy': ['Rome', 'Milan', 'Naples', 'Turin', 'Palermo', 'Genoa', 'Bologna', 'Florence', 'Venice'],
  'netherlands': ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht', 'Eindhoven'],
  'portugal': ['Lisbon', 'Porto', 'Braga', 'Coimbra', 'Faro'],
  'poland': ['Warsaw', 'Krakow', 'Wroclaw', 'Poznan', 'Gdansk', 'Lodz'],
  'russia': ['Moscow', 'Saint Petersburg', 'Novosibirsk', 'Yekaterinburg', 'Kazan'],
  'ukraine': ['Kyiv', 'Kharkiv', 'Odesa', 'Lviv', 'Dnipro'],
  'greece': ['Athens', 'Thessaloniki', 'Patras', 'Heraklion'],
  'indonesia': ['Jakarta', 'Surabaya', 'Bandung', 'Medan', 'Semarang', 'Makassar', 'Denpasar', 'Yogyakarta'],
  'malaysia': ['Kuala Lumpur', 'George Town', 'Johor Bahru', 'Ipoh', 'Shah Alam', 'Kota Kinabalu', 'Kuching', 'Malacca'],
  'singapore': ['Singapore'],
  'thailand': ['Bangkok', 'Chiang Mai', 'Pattaya', 'Phuket', 'Khon Kaen', 'Hat Yai'],
  'philippines': ['Manila', 'Quezon City', 'Cebu City', 'Davao City', 'Makati', 'Baguio'],
  'vietnam': ['Ho Chi Minh City', 'Hanoi', 'Da Nang', 'Hai Phong', 'Can Tho', 'Hue'],
  'japan': ['Tokyo', 'Osaka', 'Yokohama', 'Nagoya', 'Sapporo', 'Fukuoka', 'Kyoto', 'Kobe'],
  'south korea': ['Seoul', 'Busan', 'Incheon', 'Daegu', 'Daejeon', 'Gwangju'],
  'china': ['Beijing', 'Shanghai', 'Guangzhou', 'Shenzhen', 'Chengdu', 'Hangzhou', 'Wuhan', 'Xian'],
  'nigeria': ['Lagos', 'Abuja', 'Kano', 'Ibadan', 'Port Harcourt', 'Benin City'],
  'kenya': ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru'],
  'south africa': ['Johannesburg', 'Cape Town', 'Durban', 'Pretoria', 'Port Elizabeth', 'Bloemfontein'],
  'ghana': ['Accra', 'Kumasi', 'Tamale'],
  'ethiopia': ['Addis Ababa', 'Dire Dawa'],
  'tanzania': ['Dar es Salaam', 'Dodoma', 'Arusha', 'Zanzibar City'],
  'morocco': ['Casablanca', 'Rabat', 'Marrakesh', 'Fes', 'Tangier', 'Agadir'],
  'brazil': ['Sao Paulo', 'Rio de Janeiro', 'Brasilia', 'Salvador', 'Fortaleza', 'Belo Horizonte', 'Curitiba', 'Recife'],
  'mexico': ['Mexico City', 'Guadalajara', 'Monterrey', 'Puebla', 'Tijuana', 'Cancun', 'Merida'],
  'argentina': ['Buenos Aires', 'Cordoba', 'Rosario', 'Mendoza'],
  'colombia': ['Bogota', 'Medellin', 'Cali', 'Barranquilla', 'Cartagena'],
  'chile': ['Santiago', 'Valparaiso', 'Concepcion'],
  'peru': ['Lima', 'Arequipa', 'Cusco', 'Trujillo'],
  'iran': ['Tehran', 'Mashhad', 'Isfahan', 'Shiraz', 'Tabriz'],
  'iraq': ['Baghdad', 'Basra', 'Erbil', 'Mosul', 'Najaf'],
  'afghanistan': ['Kabul', 'Herat', 'Kandahar', 'Mazar-i-Sharif'],
  'uzbekistan': ['Tashkent', 'Samarkand', 'Bukhara'],
  'kazakhstan': ['Almaty', 'Astana', 'Shymkent'],
  'azerbaijan': ['Baku', 'Ganja', 'Sumqayit'],
  'ireland': ['Dublin', 'Cork', 'Galway', 'Limerick'],
  'belgium': ['Brussels', 'Antwerp', 'Ghent', 'Bruges'],
  'switzerland': ['Zurich', 'Geneva', 'Basel', 'Bern', 'Lausanne'],
  'austria': ['Vienna', 'Graz', 'Linz', 'Salzburg', 'Innsbruck'],
  'sweden': ['Stockholm', 'Gothenburg', 'Malmo', 'Uppsala'],
  'norway': ['Oslo', 'Bergen', 'Trondheim', 'Stavanger'],
  'denmark': ['Copenhagen', 'Aarhus', 'Odense', 'Aalborg'],
  'finland': ['Helsinki', 'Espoo', 'Tampere', 'Turku'],
  'czechia': ['Prague', 'Brno', 'Ostrava', 'Plzen'],
  'romania': ['Bucharest', 'Cluj-Napoca', 'Timisoara', 'Iasi'],
  'hungary': ['Budapest', 'Debrecen', 'Szeged'],
  'israel': ['Tel Aviv', 'Jerusalem', 'Haifa', 'Beersheba']
};

export function citiesForCountry(country) {
  return CITIES[String(country || '').trim().toLowerCase()] || [];
}
