export const CSV_COLUMNS = [
  'g_place_id', 'g_cid', 'g_name', 'g_subtitle', 'g_category',
  'g_categories', 'g_address', 'g_street', 'g_neighborhood', 'g_city',
  'g_state', 'g_postal_code', 'g_country_code', 'g_plus_code',
  'g_located_in', 'g_phone', 'g_website', 'g_menu_image_urls', 'g_image_url', 'g_lat', 'g_lng',
  'g_rating', 'g_price_level', 'g_hours', 'g_temporarily_closed',
  'g_permanently_closed', 'g_is_ad',
  'g_additional_info', 'g_popular_times', 'g_live_busyness_percent',
  'g_live_busyness_text', 'verified_at', 'confidence'
];

export function createPlaceRecord(search = {}) {
  return {
    g_place_id: null,
    g_cid: null,
    g_name: null,
    g_subtitle: null,
    g_category: null,
    g_categories: [],
    g_address: null,
    g_street: null,
    g_neighborhood: null,
    g_city: null,
    g_state: null,
    g_postal_code: null,
    g_country_code: null,
    g_plus_code: null,
    g_located_in: null,
    g_phone: null,
    g_website: null,
    g_menu_image_urls: [],
    g_image_url: null,
    g_lat: null,
    g_lng: null,
    distance_m: null,
    g_rating: null,
    g_price_level: null,
    g_hours: null,
    g_temporarily_closed: null,
    g_permanently_closed: null,
    g_is_ad: null,
    g_rank: null,
    g_maps_url: null,
    g_additional_info: null,
    g_popular_times: null,
    g_live_busyness_percent: null,
    g_live_busyness_text: null,
    search_term: search.term ?? '',
    search_lat: search.lat ?? null,
    search_lng: search.lng ?? null,
    search_radius_m: search.radius_m ?? null,
    verified_at: new Date().toISOString(),
    confidence: null
  };
}
